services:
  - type: web
    name: buspass-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn buspassmangment.wsgi:application"
    autoDeploy: true
    branch: main
    plan: free
